### PR TITLE
Add modpack folder so recipes don't bug out.

### PR DESCRIPTION
**Pull request by Time6628**
If you don't put the minetweaker scripts in the modpack/default folder, the recipes will bug out and not work.

### CODE REVIEW

**Comment by BBoldt** [comment]
This is something to do with FTBUtils, isn't it?

I didn't know it stopped default minetweaker configs from working despite being in the right location...

Thanks for pointing it out, I'll look into this for the next release.

**Comment by Time6628** [comment]
Yea, FTBUtils pretty much breaks minetweaker unless you put the recipes in the right places.

**Comment by Time6628** [comment]
Could you merge this pull please? The pack is pretty much unplayable on servers, because the recipes don't sync properly with the client and it causes tons of issues.

**Comment by BBoldt** [comment]
I have a day off tomorrow, I'll get it done then.

**Comment by BBoldt** [comment]
@Time6628 Did you actually test and prove that recipes weren't working without the modpack/default folder on servers?

I talked to the mod creator about this and he said neither FTBUtils nor FTBLib mess with minetweaker at all. 

The mod which is responsible for doing that is FTB Tweaks, which Unabridged does not have: https://minecraft.curseforge.com/projects/ftb-tweaks

**Comment by Time6628** [comment]
Yes, the recipes bugged out after a few hours of the server being up. After the latest update when the recipes were in the modpack folder on both client and server, it no longer happens.

**Comment by BBoldt** [comment]
@LatvianModder, care to chime in here?

**Comment by LatvianModder** [comment]
FTBTweaks loads recipe scripts from /modpack/<mode>/scripts. If FTBTweaks isnt installed, MineTweaker loads scripts from /scripts/

**Comment by LatvianModder** [comment]
If you dont have multiple packmodes (like Normal & Evolved on Infinty) dont use FTBTweaker, it can mess up a lot :P

**Comment by BBoldt** [comment]
So, I should remove the modpack/scripts/ folder considering I do not have FTB Tweaks at all and never have had it?

I think @Time6628 has just run an infinity evolved server before and thinks my pack is the same.

Time, can you prove none of my minetweaker scripts were working on your server without the /modpack/scripts/ folder? Because I don't believe you. It's a waste of my time to continually copy/paste all the scripts to a folder that is not even being used according to the mod author.

**Comment by Time6628** [comment]
When the scripts were not in the modpack folder, after a certain amount of time the recipes would no longer sync, because the client and server scripts were different some how. 
Server other server owners have noted that with FTBUtilities, if the scripts are different most recipes just no longer work. I have no idea why, or how this occurs, but it occurs. 
Here's a stall report from the Unabridged version 13 update, https://gist.github.com/Time6628/17d3cea0145e8ddb6408cdd37651ee0e 
it occurs everytime someone tries to craft something in an AE2 crafting terminal. 
And in a normal crafting table, the recipe "crafts", meaning it takes the items in the table but does not give the output. 
I have no idea why or how this occurs, but ever since 13a, there have been very very few recipes bugs like that.

**Comment by Time6628** [comment]
I'm going to assume it's related to this bug https://github.com/LatvianModder/FTBLib/issues/20

**Comment by BBoldt** [comment]
How can that be though if FTBLib & FTBUtils do not touch minetweaker scripts at all?

**Comment by Time6628** [comment]
Do not know.

**Pull request merged**
